config/routes.rb
Rails.application.routes.draw do

devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' },
controllers: {omniauth_callbacks: 'omniauth_callbacks'}

   # 'users/omniauth_callbacks' }
# omniauth_callbacks: 'google' }

# ,

root to: 'home#index'

resources :users
resources :players
resources :games do
end

namespace :api do
  namespace :v1 do
    resources :users
    resources :games
    resources :players
    resources :scores
    resources :home

      end
    end
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Cricket</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="icon" type="image/ico" href="<%= asset_path('favicon.ico') %>" />

</head>

<body>
  <% if notice %>
    <div class="success callout" data-closable><%= notice %>
      <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <div class="top-bar">
    <div class="top-bar-left">
         <h1>
           <%= link_to "CRICKET", root_path, class: "header-text" %>
         </h1>
    </div>
  </div>

<% if current_user %>
  <div class="title-bar">
    <div class="title-bar-left">
    <ul class="menu">
        <li><%= link_to "Profile", user_path(current_user)   %></li>
        <li><%= link_to "New Game", new_game_path  %></li>
        <li><%= link_to "Games", games_path  %></li>
        <li><%= link_to "Players", players_path %></li>
      </ul>
    </div>
    <div class="title-bar-right">
      <ul class="dropdown menu" data-dropdown-menu>
      <li class="username">
          <a href="#"><%= current_user.player.name %></a>
          <ul class="menu-vertical">
            <li><%= link_to "Log Out", destroy_user_session_path, method: "delete" %></li>
          </div>
        </div>
      <% end %>

<div id="app"></div>

    <%= yield %>

</body>
</html>